(package "blacken"
         "0.2.0"
         "Reformat python buffers using the \"black\" formatter")

(website-url "https://github.com/proofit404/blacken")
(keywords "convenience" "blacken")

(package-file "blacken.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "gnu")

(depends-on "emacs" "25.2")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
